pipelines:
  integration:
    group: contacts-app
    materials:
      frontend-package:
        pipeline: frontend-compile
        stage: build
      api-package:
        pipeline: api-compile
        stage: build
      mygit:  # this is the name of material
        git: https://github.com/ckaushik/contacts-api.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
                - exec: # indicates type of task
                   command: bash
                   arguments:
                     - "-c"
                     - "echo yarn install and npm test"
              resources:
                - yarn
